trigger:
- main

pool:
  name: mysky

steps:
- script: echo "Stage 1 - Setting up Java version."

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml' # Adjusted path to match Maven output structure
    goals: 'package'

- script: echo "Stage 2 - Maven build and test completed successfully."

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'my-java-artifacts'
    publishLocation: 'Container'

- script: echo "Stage 3 - Artifacts published successfully."

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/target/surefire-reports/TEST-*.xml' # Adjusted path to match Maven output structure
    failTaskOnFailedTests: true

- script: echo "Regression test is successfully completed."
