trigger:
- main

pool: mysky

steps:
- script: echo "Stage 1 - Setting up Java version."
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkArchitectureOption: 'x64'
    **publishJUnitResults: true**  # Ensure JUnit results are published
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Correct path pattern
    goals: 'test'  # Use 'test' goal to run tests

- script: echo "Stage 2 - Maven build and test completed successfully."
  **condition: succeeded()**  # Conditionally run only if Maven succeeds

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
    ArtifactName: 'my-java-artifacts'
    publishLocation: 'container'

- script: echo "Stage 3 - Artifacts published successfully."

- task: PublishTestResults@2
  **condition: succeeded()**  # Conditionally run only if Maven succeeds
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/surefire-reports/TEST-*.xml'  # Correct path pattern
    failTaskOnFailedTests: true
    searchFolder: '$(System.DefaultWorkingDirectory)'

- script: echo "Regression test is successfully completed."
  **condition: succeeded()**  # Conditionally run only if previous stages succeed
